package dart.restaurante.views;

import dart.restaurante.controller.ClienteJpaController;
import dart.restaurante.controller.CompraJpaController;
import dart.restaurante.controller.DetalleCompraJpaController;
import dart.restaurante.controller.ProductoJpaController;
import dart.restaurante.controller.ProveedorJpaController;
import dart.restaurante.controller.UsuarioJpaController;
import dart.restaurante.dao.Cliente;
import dart.restaurante.dao.Compra;
import dart.restaurante.dao.DetalleCompra;
import dart.restaurante.dao.Producto;
import dart.restaurante.dao.Proveedor;
import dart.restaurante.dao.Usuario;
import static dart.restaurante.views.Inicio.SesionUsuario;
import static dart.restaurante.views.Inicio.lblBienvenida;
import static dart.restaurante.views.Login.idUsuario;
import java.awt.Font;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Diego Ramos
 */
public class FormCrearCompra extends javax.swing.JFrame {

    EntityManagerFactory emf;
    ProveedorJpaController ProveedorEntityManager;
    UsuarioJpaController UsuarioEntityManager;
    CompraJpaController CompraEntityManager;
    DetalleCompraJpaController DetalleCompraEntityManager;
    ProductoJpaController ProductoEntityManager;

    public static String idProveedor = "";
    String idCompra = "";
    public static Double TotalCompra = 0.0;
    Boolean banderaDescuento = true;

    //public static TableRowSorter<DefaultTableModel> sorter;
    public FormCrearCompra() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/pngwing.png")).getImage());
        //this.setExtendedState(MAXIMIZED_BOTH);
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        model.setRowCount(0); //eliminar filas existentes
        emf = Persistence.createEntityManagerFactory("dart.restaurante.asados_Asados_jar_1.0-SNAPSHOTPU");
        ProveedorEntityManager = new ProveedorJpaController(emf);
        UsuarioEntityManager = new UsuarioJpaController(emf);
        CompraEntityManager = new CompraJpaController(emf);
        DetalleCompraEntityManager = new DetalleCompraJpaController(emf);
        ProductoEntityManager = new ProductoJpaController(emf);
        
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/YYYY");
        txtFechaRegistro.setText(sdf.format(d));
        
        InicioSesion();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlProductos = new javax.swing.JPanel();
        txtFechaRegistro = new javax.swing.JTextField();
        lblFechaRegistro = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnAgregarProd = new javax.swing.JButton();
        btnSeleccionarProd = new javax.swing.JButton();
        lblTotalPagar = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        btnEliminarFila = new javax.swing.JButton();
        pnlLeft = new javax.swing.JPanel();
        btnCrearCompra = new javax.swing.JButton();
        btnCancelarCompra = new javax.swing.JButton();
        btnRegresarCompra = new javax.swing.JButton();
        jPnlUsuario = new javax.swing.JPanel();
        lblNITUsuario = new javax.swing.JLabel();
        txtNITUsuario = new javax.swing.JTextField();
        lblNombreUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jPnlProveedor = new javax.swing.JPanel();
        lblNITProveedor = new javax.swing.JLabel();
        txtNITProveedor = new javax.swing.JTextField();
        lblNombreProveedor = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        btnAgregarProv = new javax.swing.JButton();
        btnSeleccionarProv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnlProductos.setBackground(new java.awt.Color(129, 164, 220));
        jPnlProductos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N
        jPnlProductos.setPreferredSize(new java.awt.Dimension(931, 522));

        txtFechaRegistro.setEditable(false);
        txtFechaRegistro.setBackground(new java.awt.Color(129, 164, 220));
        txtFechaRegistro.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtFechaRegistro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        lblFechaRegistro.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblFechaRegistro.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaRegistro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaRegistro.setText("Fecha de Registro:");

        tblProductos.setBackground(new java.awt.Color(204, 204, 204));
        tblProductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 102, 255)));
        tblProductos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblProductos.setForeground(new java.awt.Color(0, 0, 0));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Categoria", "Unidad", "Precio Compra", "Precio Venta", "Cantidad", "Total Compra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblProductos.setGridColor(new java.awt.Color(0, 0, 0));
        tblProductos.setSelectionBackground(new java.awt.Color(255, 255, 204));
        tblProductos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblProductos.setShowGrid(true);
        tblProductos.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblProductos.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblProductos.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblProductos.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblProductos.getColumnModel().getColumn(4).setPreferredWidth(150);
            tblProductos.getColumnModel().getColumn(5).setPreferredWidth(150);
            tblProductos.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblProductos.getColumnModel().getColumn(7).setPreferredWidth(150);
        }

        btnAgregarProd.setBackground(new java.awt.Color(129, 164, 220));
        btnAgregarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0prod_add.png"))); // NOI18N
        btnAgregarProd.setToolTipText("Agregar");
        btnAgregarProd.setBorder(null);
        btnAgregarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProdActionPerformed(evt);
            }
        });

        btnSeleccionarProd.setBackground(new java.awt.Color(129, 164, 220));
        btnSeleccionarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0select_110958.png"))); // NOI18N
        btnSeleccionarProd.setToolTipText("Seleccionar");
        btnSeleccionarProd.setBorder(null);
        btnSeleccionarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProdActionPerformed(evt);
            }
        });

        lblTotalPagar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTotalPagar.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalPagar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalPagar.setText("Total a pagar:");

        txtTotalPagar.setEditable(false);
        txtTotalPagar.setBackground(new java.awt.Color(129, 164, 220));
        txtTotalPagar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTotalPagar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));
        txtTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPagarActionPerformed(evt);
            }
        });

        btnEliminarFila.setBackground(new java.awt.Color(129, 164, 220));
        btnEliminarFila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delFila.png"))); // NOI18N
        btnEliminarFila.setToolTipText("Eliminar");
        btnEliminarFila.setBorder(null);
        btnEliminarFila.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlProductosLayout = new javax.swing.GroupLayout(jPnlProductos);
        jPnlProductos.setLayout(jPnlProductosLayout);
        jPnlProductosLayout.setHorizontalGroup(
            jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlProductosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarProd)
                    .addComponent(btnSeleccionarProd)
                    .addComponent(btnEliminarFila))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlProductosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPnlProductosLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(lblFechaRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlProductosLayout.setVerticalGroup(
            jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlProductosLayout.createSequentialGroup()
                .addGroup(jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaRegistro)
                    .addComponent(txtFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlProductosLayout.createSequentialGroup()
                        .addComponent(btnAgregarProd)
                        .addGap(4, 4, 4)
                        .addComponent(btnSeleccionarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnEliminarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pnlLeft.setBackground(new java.awt.Color(129, 164, 220));

        btnCrearCompra.setBackground(new java.awt.Color(129, 164, 220));
        btnCrearCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0shopping-cart-add-button_icon-icons.com_56132.png"))); // NOI18N
        btnCrearCompra.setToolTipText("Crear Compra");
        btnCrearCompra.setBorder(null);
        btnCrearCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCompraActionPerformed(evt);
            }
        });

        btnCancelarCompra.setBackground(new java.awt.Color(129, 164, 220));
        btnCancelarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0shopping-cart-cancel-button_icon-icons.com_56130.png"))); // NOI18N
        btnCancelarCompra.setToolTipText(" Cancelar Compra");
        btnCancelarCompra.setBorder(null);
        btnCancelarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCompraActionPerformed(evt);
            }
        });

        btnRegresarCompra.setBackground(new java.awt.Color(129, 164, 220));
        btnRegresarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0undo_111005.png"))); // NOI18N
        btnRegresarCompra.setToolTipText("Regresar");
        btnRegresarCompra.setBorder(null);
        btnRegresarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftLayout.createSequentialGroup()
                .addContainerGap(508, Short.MAX_VALUE)
                .addComponent(btnCrearCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresarCompra)
                .addGap(20, 20, 20))
        );

        jPnlUsuario.setBackground(new java.awt.Color(129, 164, 220));
        jPnlUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N
        jPnlUsuario.setPreferredSize(new java.awt.Dimension(931, 522));

        lblNITUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblNITUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblNITUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNITUsuario.setText("NIT del Usuario:");

        txtNITUsuario.setEditable(false);
        txtNITUsuario.setBackground(new java.awt.Color(129, 164, 220));
        txtNITUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNITUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        lblNombreUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreUsuario.setText("Nombre del Usuario:");

        txtNombreUsuario.setEditable(false);
        txtNombreUsuario.setBackground(new java.awt.Color(129, 164, 220));
        txtNombreUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNombreUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        javax.swing.GroupLayout jPnlUsuarioLayout = new javax.swing.GroupLayout(jPnlUsuario);
        jPnlUsuario.setLayout(jPnlUsuarioLayout);
        jPnlUsuarioLayout.setHorizontalGroup(
            jPnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUsuarioLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jPnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNITUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNITUsuario))
                .addGap(32, 32, 32)
                .addGroup(jPnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreUsuario)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPnlUsuarioLayout.setVerticalGroup(
            jPnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUsuarioLayout.createSequentialGroup()
                .addGroup(jPnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNITUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNITUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPnlProveedor.setBackground(new java.awt.Color(129, 164, 220));
        jPnlProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N
        jPnlProveedor.setPreferredSize(new java.awt.Dimension(931, 522));

        lblNITProveedor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblNITProveedor.setForeground(new java.awt.Color(0, 0, 0));
        lblNITProveedor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNITProveedor.setText("NIT del Proveedor:");

        txtNITProveedor.setEditable(false);
        txtNITProveedor.setBackground(new java.awt.Color(129, 164, 220));
        txtNITProveedor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNITProveedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        lblNombreProveedor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblNombreProveedor.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreProveedor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreProveedor.setText("Nombre del Proveedor:");

        txtNombreProveedor.setEditable(false);
        txtNombreProveedor.setBackground(new java.awt.Color(129, 164, 220));
        txtNombreProveedor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNombreProveedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        btnAgregarProv.setBackground(new java.awt.Color(129, 164, 220));
        btnAgregarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0personadd_111023.png"))); // NOI18N
        btnAgregarProv.setToolTipText("Agregar");
        btnAgregarProv.setBorder(null);
        btnAgregarProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProvActionPerformed(evt);
            }
        });

        btnSeleccionarProv.setBackground(new java.awt.Color(129, 164, 220));
        btnSeleccionarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0personselect_110958.png"))); // NOI18N
        btnSeleccionarProv.setToolTipText("Seleccionar");
        btnSeleccionarProv.setBorder(null);
        btnSeleccionarProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlProveedorLayout = new javax.swing.GroupLayout(jPnlProveedor);
        jPnlProveedor.setLayout(jPnlProveedorLayout);
        jPnlProveedorLayout.setHorizontalGroup(
            jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarProv)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionarProv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNITProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNITProveedor))
                .addGap(32, 32, 32)
                .addGroup(jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreProveedor)
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlProveedorLayout.setVerticalGroup(
            jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlProveedorLayout.createSequentialGroup()
                .addGroup(jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlProveedorLayout.createSequentialGroup()
                        .addGroup(jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarProv)
                            .addComponent(btnSeleccionarProv))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPnlProveedorLayout.createSequentialGroup()
                        .addGroup(jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNITProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombreProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNITProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)
                    .addComponent(jPnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)
                    .addComponent(jPnlProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnlProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPnlProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCompraActionPerformed
        if (!Vacio()) {
            Compra();//seteando datos de la compra

        } else {
            JOptionPane.showMessageDialog(null, "Campos vacios, no se pudo crear la compra");
        }
    }//GEN-LAST:event_btnCrearCompraActionPerformed

    private void btnRegresarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarCompraActionPerformed
        Inicio in = new Inicio();
        in.setVisible(true);
        this.dispose();
        //commit
    }//GEN-LAST:event_btnRegresarCompraActionPerformed

    private void btnSeleccionarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProdActionPerformed
        ListarProductoCompra lpc = new ListarProductoCompra(this, true);
        lpc.setVisible(true);
    }//GEN-LAST:event_btnSeleccionarProdActionPerformed

    private void btnAgregarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProdActionPerformed
        FormCrearProductoCompra fcpc = new FormCrearProductoCompra(this, true);
        fcpc.setVisible(true);

    }//GEN-LAST:event_btnAgregarProdActionPerformed

    private void btnAgregarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProvActionPerformed
        FormCrearProveedorCompra fcp = new FormCrearProveedorCompra(this, true);
        fcp.setVisible(true);
    }//GEN-LAST:event_btnAgregarProvActionPerformed

    private void btnSeleccionarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProvActionPerformed
        ListarProveedoresCompra lpc = new ListarProveedoresCompra(this, true);
        lpc.setVisible(true);
    }//GEN-LAST:event_btnSeleccionarProvActionPerformed

    private void btnCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCompraActionPerformed

        txtFechaRegistro.setText("");
        txtNITProveedor.setText("");
        txtNombreProveedor.setText("");
        txtTotalPagar.setText("");
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        model.setRowCount(0); //eliminar filas existentes
        JOptionPane.showMessageDialog(null, "La compra se ha cancelado");
    }//GEN-LAST:event_btnCancelarCompraActionPerformed

    private void btnEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFilaActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        //model.removeRow(tblProductos.getSelectedRow());
       
        int fila = tblProductos.getSelectedRow();
        if (fila != -1) {
            Double cantEliminada = Double.valueOf(tblProductos.getValueAt(fila, 7).toString());
            TotalCompra = Double.valueOf(txtTotalPagar.getText());
            TotalCompra = TotalCompra-cantEliminada;
            txtTotalPagar.setText(TotalCompra.toString());
            TotalCompra = 0.0;
            model.removeRow(tblProductos.getSelectedRow());
            JOptionPane.showMessageDialog(null, "El Producto se ha eliminado de la Compra");
        } else {
            JOptionPane.showMessageDialog(null, "No se ha selccionado ningun Producto");
        }
    }//GEN-LAST:event_btnEliminarFilaActionPerformed

    private void txtTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPagarActionPerformed

    private Boolean Vacio() {
        return  txtNITProveedor.getText().isEmpty()
                && txtNombreProveedor.getText().isEmpty()  
                && txtTotalPagar.getText().isEmpty() && tblProductos.getRowCount() == 0;
    }

    public void InicioSesion() {
        System.out.println("id usuario desde compra inicio" + idUsuario);
        Usuario u = UsuarioEntityManager.findUsuario(idUsuario);
        txtNITUsuario.setText(u.getNit());
        txtNombreUsuario.setText(u.getNombre());
    }

    

    public static void DatosProveedor(String id, String nitProveedor, String nombreProveedor) {
        idProveedor = id;
        txtNITProveedor.setText(nitProveedor);
        txtNombreProveedor.setText(nombreProveedor);
    }

    public static void DatosProducto(String codigo, String nombre, String categoria, String unidad,  Double precioCompra, Double precioVenta, int stock) {
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();

        //model.setRowCount(0); //eliminar filas existentes
        tblProductos.setDefaultRenderer(Object.class, new Render());
        Object newRow[] = {codigo, nombre, categoria,  unidad,  precioCompra, precioVenta, stock, precioCompra * stock};
        model.addRow(newRow);

        for (int i = 0; i < tblProductos.getRowCount(); i++) {
            TotalCompra += Double.parseDouble(tblProductos.getValueAt(i, 7).toString());
        }
        txtTotalPagar.setText(TotalCompra.toString());
        TotalCompra = 0.0;
    }

    private void Compra() {
        Integer cant = 0;
        Double total = 0.0;
        Compra c = new Compra();
        Usuario u = new Usuario();
        Proveedor p = new Proveedor();
        
        
        
        p.setId(idProveedor);
       
        u.setId(idUsuario);
        
        

        String id = UUID.randomUUID().toString();
        idCompra = id;
        c.setId(id);
        c.setIdUsuario(u);
        c.setIdProveedor(p);
        //seteando Fecha
        try {
            //seteando la fecha
            Date dt = new SimpleDateFormat("dd/MM/yyyy")
                    .parse(txtFechaRegistro.getText());
            c.setFechaCompra(dt);;
        } catch (ParseException ex) {
            //Logger.getLogger(CrearFactura.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Fecha mal ingresada");
        }
        for (int i = 0; i < tblProductos.getRowCount(); i++) {
            cant += Integer.valueOf(tblProductos.getValueAt(i, 6).toString());
            total += Double.valueOf(tblProductos.getValueAt(i, 7).toString());
        }
        
        BigDecimal TotalCompra = new BigDecimal(total);
        c.setTotal(TotalCompra);
        
        System.out.println("datos compra id user"+idUsuario);
        try {
            
            CompraEntityManager.create(c);
            DatosDetalleCompra();//seteando datos detalleCompra
            JOptionPane.showMessageDialog(null, "La Compra se creó correctamente");
            FormCrearCompra fcc = new FormCrearCompra();
            fcc.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(FormCrearCompra.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "No se pudo crear la compra");
        }
        
//        lc.setId("L1");
//        BigDecimal IVA = new BigDecimal(TotalCompra.doubleValue()*0.12);
//        lc.setIVAcredito(IVA);
//        BigDecimal TotalLibroCompra = new BigDecimal(TotalCompra.doubleValue()+IVA.doubleValue());
//        lc.setTotal(TotalLibroCompra);
//        
//        try {
//            LibroCompraEntityManager.edit(lc);
//        } catch (Exception ex) {
//            Logger.getLogger(FormCrearCompra.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
//        lc.setId("L1");
//        BigDecimal IVA = new BigDecimal(TotalCompra.doubleValue()*0.12);
//        lc.setIVAcredito(IVA);
//        BigDecimal TotalLibroCompra = new BigDecimal(TotalCompra.doubleValue()+IVA.doubleValue());
//        lc.setTotal(TotalLibroCompra);
//        
//        try {
//            LibroCompraEntityManager.edit(lc);
//        } catch (Exception ex) {
//            Logger.getLogger(FormCrearCompra.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private void DatosDetalleCompra() {
        Producto p = new Producto();
        Producto p2 = new Producto();

        for (int i = 0; i < tblProductos.getRowCount(); i++) {
            String codigo = tblProductos.getValueAt(i, 0).toString();
            p.setNombre(tblProductos.getValueAt(i, 1).toString());
            p.setCategoria(tblProductos.getValueAt(i, 2).toString());
            p.setUnidad(tblProductos.getValueAt(i, 3).toString());
            BigDecimal precioCompra = new BigDecimal(tblProductos.getValueAt(i, 4).toString());
            BigDecimal precioVenta = new BigDecimal(tblProductos.getValueAt(i, 5).toString());
            Integer stock = Integer.valueOf(tblProductos.getValueAt(i, 6).toString());
            p.setId(codigo);
            
            p2 = ProductoEntityManager.findProducto(codigo);
            System.out.println("stock actual "+p2.getStock());          
            p.setStock(stock+p2.getStock());
            System.out.println("stock actualizado "+stock+p2.getStock());
            p.setPrecioCompra(precioCompra);
            p.setPrecioVenta(precioVenta);
            try {
                ProductoEntityManager.edit(p);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No se puede actualizar el producto");
                //Logger.getLogger(FormCrearCompra.class.getName()).log(Level.SEVERE, null, ex);
            }

            //Seteando datos detalle compra 
            DetalleCompra dc = new DetalleCompra();
            Compra c = new Compra();
            c.setId(idCompra);
            String id = UUID.randomUUID().toString();
            dc.setId(id);
            dc.setIdCompra(c);
            dc.setIdProducto(p);
            dc.setPrecioCompra(precioCompra);
            dc.setCantidad(p.getStock());
            BigDecimal totalIndividual = new BigDecimal(Double.parseDouble(p.getPrecioCompra().toString()) * p.getStock());
            dc.setTotal(totalIndividual);

            try {
                DetalleCompraEntityManager.create(dc);
            } catch (Exception ex) {
                Logger.getLogger(FormCrearCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCrearCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCrearCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCrearCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCrearCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCrearCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProd;
    private javax.swing.JButton btnAgregarProv;
    private javax.swing.JButton btnCancelarCompra;
    private javax.swing.JButton btnCrearCompra;
    private javax.swing.JButton btnEliminarFila;
    private javax.swing.JButton btnRegresarCompra;
    private javax.swing.JButton btnSeleccionarProd;
    private javax.swing.JButton btnSeleccionarProv;
    private javax.swing.JPanel jPnlProductos;
    private javax.swing.JPanel jPnlProveedor;
    private javax.swing.JPanel jPnlUsuario;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFechaRegistro;
    private javax.swing.JLabel lblNITProveedor;
    private javax.swing.JLabel lblNITUsuario;
    private javax.swing.JLabel lblNombreProveedor;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JPanel pnlLeft;
    public static javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtFechaRegistro;
    public static javax.swing.JTextField txtNITProveedor;
    public static javax.swing.JTextField txtNITUsuario;
    public static javax.swing.JTextField txtNombreProveedor;
    public static javax.swing.JTextField txtNombreUsuario;
    public static javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
