/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dart.restaurante.views;

import dart.restaurante.controller.AperturaJpaController;
import dart.restaurante.controller.CierreJpaController;
import dart.restaurante.dao.Apertura;
import dart.restaurante.dao.Cierre;
import static dart.restaurante.views.FormApertura.tblListarAperturas;

//import dart.restaurante.views.ListarInventario.tblListarProductos;
import java.awt.Font;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Diego Ramos
 */
public class FormCierre extends javax.swing.JDialog {

    /**
     * Creates new form ListarProductoCompra
     */
    EntityManagerFactory emf;
   CierreJpaController CierreEntityManager;
   private Boolean bandera = false;
    public static TableRowSorter<DefaultTableModel> sorter;
    public FormCierre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/pngwing.png")).getImage());
        //this.setExtendedState(MAXIMIZED_BOTH);
        tblListarCierres.getTableHeader().setFont(new Font("Arial", Font.PLAIN, 20));

        emf = Persistence.createEntityManagerFactory("dart.restaurante.asados_Asados_jar_1.0-SNAPSHOTPU");
        CierreEntityManager = new CierreJpaController(emf);
        
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/YYYY");
        txtFechaCierre.setText(sdf.format(d));
        ListarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarCierres = new javax.swing.JTable();
        txtFechaCierre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblCodin6 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblCodin7 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        pnlLeft = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1230, 712));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(129, 164, 220));
        jPanel1.setPreferredSize(new java.awt.Dimension(931, 522));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Cierre");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0buscar.png"))); // NOI18N

        tblListarCierres.setBackground(new java.awt.Color(255, 255, 255));
        tblListarCierres.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 102, 255)));
        tblListarCierres.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblListarCierres.setForeground(new java.awt.Color(0, 0, 0));
        tblListarCierres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Fecha", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListarCierres.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tblListarCierres.setGridColor(new java.awt.Color(153, 255, 153));
        tblListarCierres.setSelectionBackground(new java.awt.Color(255, 255, 204));
        tblListarCierres.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblListarCierres.setShowGrid(true);
        tblListarCierres.setShowVerticalLines(false);
        tblListarCierres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListarCierresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListarCierres);

        txtFechaCierre.setEditable(false);
        txtFechaCierre.setBackground(new java.awt.Color(129, 164, 220));
        txtFechaCierre.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtFechaCierre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaCierre.setBorder(null);
        txtFechaCierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaCierreMouseClicked(evt);
            }
        });
        txtFechaCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaCierreActionPerformed(evt);
            }
        });

        lblCodin6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCodin6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodin6.setText("Fecha de Cierre");

        lblNombre.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        txtMonto.setBackground(new java.awt.Color(129, 164, 220));
        txtMonto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMonto.setBorder(null);
        txtMonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMontoMouseClicked(evt);
            }
        });
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        lblCodin7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCodin7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodin7.setText("Monto de cierre");

        btnGuardar.setBackground(new java.awt.Color(129, 164, 220));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guardarCheque.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setBorder(null);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(lblCodin6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFechaCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(lblCodin7))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 44, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCodin6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCodin7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 0, 1150, 680));

        pnlLeft.setBackground(new java.awt.Color(129, 164, 220));

        btnRegresar.setBackground(new java.awt.Color(129, 164, 220));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0undo_111005.png"))); // NOI18N
        btnRegresar.setToolTipText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftLayout.createSequentialGroup()
                .addContainerGap(622, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Double Monto = 0.0;
        
        if(!txtMonto.getText().isEmpty()){
        if(tblListarCierres.getRowCount() != 0){
        for (int i = 0; i < tblListarCierres.getRowCount(); i++) {
            if(txtFechaCierre.getText().equals(tblListarCierres.getValueAt(i, 1))){
            Monto = Double.valueOf(tblListarCierres.getValueAt(i, 2).toString());
                if(Monto == 0){
                    bandera = false;
                    break;
            }else{
                bandera = true;
                break;
                }
            }
        }
        
        if(!bandera){
            
            SaveCierre();
          
        }else{
        JOptionPane.showMessageDialog(null, "Ya se ha ha realizado el cierre");
        }
       }else{SaveCierre();}
        }else{JOptionPane.showMessageDialog(null, "Falta el monto a agregar");}
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtFechaCierreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaCierreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaCierreMouseClicked

    private void txtFechaCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaCierreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaCierreActionPerformed

    private void tblListarCierresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListarCierresMouseClicked
       
    }//GEN-LAST:event_tblListarCierresMouseClicked

    private void txtMontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMontoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoMouseClicked

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed
    

   
   private void ListarProductos(){
    DefaultTableModel model = (DefaultTableModel) tblListarCierres.getModel();
    List<Cierre> cierre = CierreEntityManager.findCierreEntities();
    model.setRowCount(0); //eliminar filas existentes
    tblListarCierres.setDefaultRenderer(Object.class, new Render());
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/YYYY");
    
    for(Cierre c : cierre){
        
        
        Object newRow[] = {c.getId(),sdf.format(c.getFechaCierre()),c.getMonto()};
        model.addRow(newRow);
        
    } 
    tblListarCierres.setAutoCreateRowSorter(true);
    sorter = new TableRowSorter<>(model);
        tblListarCierres.setRowSorter(sorter);
    }
   
    private void filtrar(String cadena) {

        sorter.setRowFilter(RowFilter.regexFilter(cadena.toUpperCase()));

    }
    
    private void SaveCierre(){
    
    Date d = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");     
    List<Cierre> cierre = CierreEntityManager.findCierreFechaEntities(sdf.format(d));    
    Cierre c = new Cierre();
    
    for(Cierre cr : cierre){
        c.setId(cr.getId());
        c.setFechaCierre(cr.getFechaCierre());
    }
    c.setMonto(new BigDecimal(txtMonto.getText()));
        try {
            CierreEntityManager.edit(c);
            JOptionPane.showMessageDialog(null, "Se realizo el cierre");
            ListarProductos();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No se pudo realizar el cierre");
            //Logger.getLogger(FormCierre.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
            
            
//    c.setId(UUID.randomUUID().toString());
//    try {
//            //seteando la fecha
//            Date dt = new SimpleDateFormat("dd/MM/yyyy")
//                    .parse(txtFechaCierre.getText());
//            c.setFechaCierre(dt);
//        } catch (ParseException ex) {
//            //Logger.getLogger(CrearFactura.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(null, "Fecha mal ingresada");
//        }
//    BigDecimal monto = new BigDecimal(txtMonto.getText());
//    c.setMonto(monto);
//    
//        try {
//            CierreEntityManager.create(c);
//            JOptionPane.showMessageDialog(null, "Se aperturo, suerte en la venta");
//            ListarProductos();
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, "No se creo la apertura");
//            //Logger.getLogger(FormApertura.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    
    
    }

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormCierre dialog = new FormCierre(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCodin6;
    private javax.swing.JLabel lblCodin7;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlLeft;
    public static javax.swing.JTable tblListarCierres;
    private static javax.swing.JTextField txtFechaCierre;
    private static javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
